name: Tests

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  build-ubuntu:
    name: Ubuntu (free-threading)
    uses: ./.github/workflows/reusable-ubuntu.yml
    with:
      bolt-optimizations: false
      free-threading: true
      os: ubuntu-24.04
